=== j10y/itss/12_SynData/src/java/cn/shopin/syndata/xsd/SynData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://syndata.shopin.cn"
	xmlns:tns="http://syndata.shopin.cn" elementFormDefault="qualified">

	<include schemaLocation=""></include>

	<complexType name="SynData">
		<sequence>
			<element name="dataBase" type="tns:DataBase" />
			<element name="tableinfo" type="tns:TableInfo" />
		</sequence>
	</complexType>

	<complexType name="DataBase">
		<sequence>
			<element name="driver" type="string" />
			<element name="url" type="string" />
			<element name="username" type="string" />
			<element name="password" type="string" />
		</sequence>
	</complexType>

	<complexType name="TableInfo">
		<sequence>
			<element name="dept" type="tns:Dept" />
			<element name="user" type="tns:User" />
		</sequence>
	</complexType>

	<complexType name="Dept">
		<sequence>
			<element name="deptcode" type="string" />
			<element name="deptname" type="string" />
			<element name="parentdept" type="string" />
			<element name="startdate" type="string" />
			<element name="enddate" type="string" />
			<element name="isdelete" type="string" />
			<element name="customizeSQL" type="tns:customizeSQL" minOccurs="0"/>
		</sequence>
		<attribute name="isSyn" type="boolean" default="false"/>
		<attribute name="tablename" type="string" />
	</complexType>

	<complexType name="User">
		<sequence>
			<element name="uid" type="string" />
			<element name="email" type="string" />
			<element name="realname" type="string" />
			<element name="belongdept" type="string" />
			<element name="belongName" type="string" />
			<element name="phone" type="string" />
			<element name="mobile" type="string" />
			<element name="fax" type="string" />
			<element name="position" type="string" />
			<element name="passWord" type="tns:passWord" />
			<element name="deleteFlag" type="tns:deleteFlag" />
			<element name="customizeSQL" type="tns:customizeSQL" minOccurs="0"/>
		</sequence>
		<attribute name="isSyn" type="boolean" default="false"/>
		<attribute name="tablename" type="string" />
	</complexType>

	<complexType name="passWord">
		<attribute name="isSyn" type="boolean" default="false" />
		<attribute name="columnName" type="string" />
		<attribute name="defaultValue" type="string" />
	</complexType>
	
	<complexType name="deleteFlag">
		<attribute name="columnName" type="string" />
		<attribute name="columnType" type="string" />
		<attribute name="flagValue" type="string" />
	</complexType>

	<complexType name="customizeSQL">
		<sequence>
			<element name="value" type="string" maxOccurs="unbounded"/>
		</sequence>
	</complexType>

	<simpleType name="Mobile">
		<restriction base="integer">
			<pattern
				value="((\d{11})|^((\d{7,8})|(\d{4}|\d{3})-(\d{7,8})|(\d{4}|\d{3})-(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})|(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1}))$)">
			</pattern>
		</restriction>
	</simpleType>

	<simpleType name="Phone">
		<restriction base="integer">
			<pattern
				value="((\d{11})|^((\d{7,8})|(\d{4}|\d{3})-(\d{7,8})|(\d{4}|\d{3})-(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})|(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1}))$)">
			</pattern>
		</restriction>
	</simpleType>


	<element name="SynData" type="tns:SynData" />
	<element name="dataBase" type="tns:DataBase" />
	<element name="tableinfo" type="tns:TableInfo" />
</schema>

=== j10y/itss/12_SynData/src/java/cn/shopin/syndata/xsd/template_SynData.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
	本文件是一个模板文件，使用时请将文件名命名成如下格式：系统名_SynData.xml。
	并在部署本工程时修改配置文件中的检查目录：system.file.basepath为自己的路径。
	并将配置好的  系统名_SynData.xml 文件放置到system.file.basepath制定的路径下。
-->
<SynData xmlns="http://syndata.shopin.cn"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://syndata.shopin.cn Syndata.xsd">
	<!-- 此部分为待同步的目的数据库的链接配置 -->
	<dataBase>
		<driver></driver>
		<url></url>
		<username></username>
		<password></password>
	</dataBase>
	
	<tableinfo>
		<!-- 
			此部分为部门信息同步，其中内容需要根据实际情况配置，例如： <deptcode>departCode</deptcode>
			其中的“departCode”字段表示数据库中真是的department表的对应字段。如果没有对应字段则不填写任何值
			部门有效时间标记可以使用startDate+endDate或者是IsDelete两个标记中的其中一个。不能两个同时使用
			IsDelete字段请使用int型，1表示删除，0表示为删除。如需更新部门表，请首先将数据库中目前的部门信息设置为
			失效状态，即：endDate=当天 或者 isDelete标记为1。部门信息同步仅只会执行一次，当一次执行完毕后将会修改
			本文件<dept>节中的“isSyn”属性为false。"<customizeSQL>"节可以提供自定义SQL执行的支持，如需定义请参照
			如下格式,value可以是多个：
			<customizeSQL>
				<value>select * from xxxx</value>
			</customizeSQL>
		-->
		<dept isSyn="true" tablename="">
			<deptcode></deptcode>
			<deptname></deptname>
			<parentdept></parentdept>
			<startdate></startdate>
			<enddate></enddate>
			<isdelete></isdelete>
		</dept>
		
		<!--
			此部分用户信息同步， 同上请根据实际表对应字段填写。如需将用户信息对应密码更新为预设值时，请将
			<passWord>节“isSyn”属性设置为true并填写“defaultValue”值。否则会请将“isSyn”设定为false，以防止
			误操作。"<customizeSQL>"节可以提供自定义SQL执行的支持，如需定义请参照
			如下格式,value可以是多个：
			<customizeSQL>
				<value>select * from xxxx</value>
			</customizeSQL>
		-->
		<user isSyn="true" tablename="">
			<uid>username</uid>
			<email>email</email>
			<realname>name</realname>
			<belongdept></belongdept>
			<belongName>department_name</belongName>
			<phone>phone_number</phone>
			<mobile></mobile>
			<fax></fax>
			<position></position>
			<passWord isSyn="false" columnName="" defaultValue="" />
			<deleteFlag columnName="" columnType="int" flagValue="" />
		</user>
	</tableinfo>
</SynData>
